### PR TITLE
Bayes update

### PR DESCRIPTION
**Pull request by rdinnager**
Hi Daijiang,

Just made a few changes to the Bayesian communityPGLMM I've been meaning to do for awhile. I've removed the REML option because I decided it just doesn't make sense in a Bayesian context, and I believe that the sum to zero constraint should generally be enforced in the model (unless the intercept is suppressed, but I assume that will rarely happen, maybe I should add a warning if the intercept is removed, the model might not be valid?) I also added a few more options for the prior. Overall, it is pretty minor changes. With this change, I believe the Bayesian version will tend to produce results most similar to the REML models. But we can explore this more with simulation. Speaking of which, do you have any timeline for getting started on a paper for `phyr`? We should probably discuss how to divide up the work load for that at some point.

Cheers,
Russell

### CODE REVIEW

**Comment by daijiang** [comment]
Thanks @rdinnager !! And apologize for the delays in the paper writing. I think I will draft an outline by the end of October, and then we can pick up sections to write. I imagine that the authors will be (so far): @daijiang @rdinnager @lucasnell @arives . I think it will be a 6-8 pages paper for Methods in Ecology and Evolution. What do you think?

**Comment by rdinnager** [comment]
Sounds like a good plan to me! Cheers, 
Russell

**Comment by arives** [comment]
I think for MEE it might be expected to provide something beyond a description of the package, like analyses of performance (not necessarily speed, etc., but statistical performance). Something like a comparison of frequentist vs. Bayesian results for communityPGLMM. On the other hand, because phyr contains other things, it's not clear how to do more than a simple description. But I'm really not sure what MEE is gong to expect. Another option is Bioinformatics (where pez was published). The MEE audience is most appropriate, though.

Russell, I haven't been keeping track of the discussion, but Daijiang and I have recently updated the frequentist side of communityPGLMM to do binomial and poisson families. Also, I'm not surprised that the results from the REML version of the frequentist communityPGLMM is more similar to the Bayesian version. The frequentist version is somewhat kludged -- it uses quasi-likelihoods for the variance part that are conditional on the working estimates of the fixed effects. This makes sense for conditional quasi-likelihoods, but not for real likelihoods. So the designations of REML and ML aren't really comparable to "real" REML and ML. REML proper doesn't apply to GLMMs, since the estimation of fixed and random effects are intertwined, so REML doesn't really make sense for Bayesian analyses.

**Comment by rdinnager** [comment]
Hi Tony,

Yes, I had noticed you added binomial and poisson. The Bayesian version already supported those families from the beginning, however, the binomial family currently only supports the presence/absence encoding of the response. I need to update it to support successes/trials type of encoding, which I will work on in the near future. I also plan to implement the negative binomial and zero-inflated poisson family, which INLA can do out of the box, and possibly gamma, which should cover pretty much all the families that ecologists are likely to be interested in (except for the Tweedie distribution, but that seems to be rarely implemented).

Also, I think doing some simulation stuff and comparing the frequentist and Bayesian results would be a good idea. I have been interested lately in Michael Betancourt's "Principled Bayesian Workflow" (https://betanalpha.github.io/assets/case_studies/principled_bayesian_workflow.html), which I think has a lot of good ideas, not just for Bayesian analysis, but for any probabilistic models. As part of it, he suggests choosing summary statistics that can be used in conjunction with simulations from the model to evaluate whether the model is captures relevant structures of the data according to domain expertise. I was thinking that phylogenetic diversity metrics are perfect summary statistics for the communityPGLMMs, and so perhaps we can do a single analysis that includes both the communityPGLMM and the PD metric functionality of phyr? I thought an interesting question for example would be what is the relationship between the fitted phylogenetic variance parameters of communityPGLMM and PD metrics calculated on simulated data? Has something like this been done already? Anyway, I think there is something along these lines that could be interesting. PD metrics as summary statistics also might be an interesting way to test model adequacy (e.g. if simulated communities from a fitted model have PD values similar to those observed, the model has captured the relevant structure, at least as far as phylogeny goes, or something like that?)

**Comment by arives** [comment]
Russell,

Sorry, I should have known about the Bayes version. You'll see that Daijiang and I updated the frequentist version to pass "n", the total number of trials, since this works best for the math.

Interesting thought about comparing methods using a summary statistic. Honestly, I'm hesitant. In principle I like the idea, but it depends on what is being compared. For example, there is no universal "phylogenetic structure". In playing around for the book I just finished, when comparing simulations from OU and Pagel's lambda transforms, the results from Blomberg's K in identifying signal were very similar to the OU, but differed from lambda. In other words, K was measuring signal in the similar way to OU, even though K is a "distribution-free" assessment of signal. When looking across a large number of datasets, lambda on average seems to fit better than OU. From this, I'd be hesitant to associate "phylogenetic signal" with PD or some other measure.

Of course, if the comparisons are made for the same models fit either with frequentist or Bayes approaches, this isn't an issue so much, because phylogenetic signal will have the same structure. However, if the same models are used, it might make more sense to just compare the bias and precision of their estimates (of coefficients and variances), across a range of sample sizes. For a synoptic measure of goodness of fit, I'd use an R2, probably R2.resid from 

https://academic.oup.com/sysbio/advance-article/doi/10.1093/sysbio/syy060/5098616

or maybe R2.pred (just out of curiosity). Daijiang and I have already coded these in the package rr2.

But this does leave other pieces of phyr as outliers, like corphylo.

Cheers, Tony

**Comment by daijiang** [comment]
Hi all,
Thanks for the discussion! I think for the MEE paper: Introduction will be 1-2 paragraphs about model-based phylogenetic analyses in comparative biology and ecology, then what is the gap in the tools, then introduce phyr. Then a table of main functions in phyr separated by sections such as phylogenetic diversity, phy_cor, communityPGLMM, etc. Then some examples with potential performance comparisons that discussed here to show how to use the main functions. This probably will take ~8 pages and should be a good size for a package paper.

Thanks @rdinnager for the bayesian part. Let me know if I can help with anything.

Cheers,
Daijiang

**Pull request merged**
