### PR TITLE
Morefamily

### PR DESCRIPTION
**Pull request by daijiang**
Add binomial and Poisson distributions to PGLMM

### CODE REVIEW

**Comment by arives** [comment]
If we are both working on this at the same time, things are going to get crossed, so I haven't done anything. What I want to do is have the logLik produced for glmms. You have to use these logLik carefully, but for comparing models with the same fixed effects, they are useful.


Daijiang,

I've found a few minor problems that lead to warnings(). I've fixed them and will push the changes. I just have to remember where they are, since I've been working on this offline. Oh well.

Tony

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Dear Tony,
It is fine that both of us working on the same file via Github. Go ahead and work on the file you want to.
Best,
Daijiang


On Oct 1, 2018, at 2:37 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

If we are both working on this at the same time, things are going to get crossed, so I haven't done anything. What I want to do is have the logLik produced for glmms. You have to use these logLik carefully, but for comparing models with the same fixed effects, they are useful.


Daijiang,

I've found a few minor problems that lead to warnings(). I've fixed them and will push the changes. I just have to remember where they are, since I've been working on this offline. Oh well.

Tony

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
But do I make changes from the github site? Or push from the github app?

And am I being grumpy about adding the observation-level variance? I just figure that it is going to save people a lot of grief.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Either way. If you push from the github app, git pull first so that you have the latest file on your computer.

I think it is a good idea to add the observation-level one. I will add an option and set the default to TRUE so users can control it. Also, we need to analyze users’ formula first to make sure they did not set it already before we add it for them. What do you think?



On Oct 1, 2018, at 2:41 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

But do I make changes from the github site? Or push from the github app?

And am I being grumpy about adding the observation-level variance? I just figure that it is going to save people a lot of grief.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
I was just thinking of putting it in. If people really don't want it, they can use the long format for entering the covariance matrices. This will mean there is a greater chance that they know what they are doing. And it is simpler for us.

I don't think it is really necessary to check to see if there are duplicate covariance matrices. It isn't just the observation-level variance, but other terms as well (that they could enter in the long format). communityPGLMM will still work if matrices are duplicated, and the results should tell you that there is something wrong.

Do you think my simple way makes sense?

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Dear Tony,
I think it is better to give users options instead decide for them. We can set the default behavior, but they can decide whether to use it or not. So I will add the observation-level random term back, but with an additional option.
Cheers,
Daijiang


On Oct 1, 2018, at 2:50 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

I was just thinking of putting it in. If people really don't want it, they can use the long format for entering the covariance matrices. This will mean there is a greater chance that they know what they are doing. And it is simpler for us.

I don't think it is really necessary to check to see if there are duplicate covariance matrices. It isn't just the observation-level variance, but other terms as well (that they could enter in the long format). communityPGLMM will still work if matrices are duplicated, and the results should tell you that there is something wrong.

Do you think my simple way makes sense?

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
Okay. I was trying to make things simple for us (you).

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
I know! But developing a package means that we need to think more for users...

On Oct 1, 2018, at 2:57 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay. I was trying to make things simple for us (you).

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
I was a little surprised by this below – the cpp version wasn't that much faster:

> system.time(z <- communityPGLMM(count ~ 1, random.effects=attraction_repulsion_combinations_obs[[1]], family="binomial", sp = d$sp, site = d$site, data=d, REML=T, cpp=F, B.init=-1))
   user  system elapsed
 52.881   4.258  57.438

> system.time(z.cpp <- communityPGLMM(count ~ 1, random.effects=attraction_repulsion_combinations_obs[[1]], family="binomial", sp = d$sp, site = d$site, data=d, REML=T, cpp=T, B.init=-1))
   user  system elapsed
 35.544   0.215  35.743

I would have thought it would be 10x faster.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
No. Most likely will be 3-5x faster… unfortunately, I don’t know how to improve it further. Lme4 is very faster, but its structure is so complicated that I cannot follow their logics…


On Oct 1, 2018, at 3:08 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

I was a little surprised by this below – the cpp version wasn't that much faster:

> system.time(z <- communityPGLMM(count ~ 1, random.effects=attraction_repulsion_combinations_obs[[1]], family="binomial", sp = d$sp, site = d$site, data=d, REML=T, cpp=F, B.init=-1))
user system elapsed
52.881 4.258 57.438

> system.time(z.cpp <- communityPGLMM(count ~ 1, random.effects=attraction_repulsion_combinations_obs[[1]], family="binomial", sp = d$sp, site = d$site, data=d, REML=T, cpp=T, B.init=-1))
user system elapsed
35.544 0.215 35.743

I would have thought it would be 10x faster.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
Lme4 uses a very different approach. The problem is that you can't do nested models their way. If you use non-nested models, then communityPGLMM is often as fast.

I also just encountered a problem. I guess pglmm_internal_cpp has to return the logLik. Would this be hard to add. Sorry.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
No problem! Should be easy to add that. Do you have the code in the R version?

Another thing, is it possible to have multiple measures for a species within each site? Currently, we can only have 1 measure for each species within each site.


On Oct 1, 2018, at 3:15 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

Lme4 uses a very different approach. The problem is that you can't do nested models their way. If you use non-nested models, then communityPGLMM is often as fast.

I also just encountered a problem. I guess pglmm_internal_cpp has to return the logLik. Would this be hard to add. Sorry.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
You've have to use the long format, and treat the covariance matrices as nested.

I was thinking that the non-nested terms could be easily generalize using something like (X|factor, cov), where cov is the covariance matrix for terms within the same factor. So the standard phylogenetic term would be (1|sp, Vphy). From the mathematical perspective, this is easy to implement. But this goes back to the original idea I had for communityPGLMM – that it should be superseded by getting lmer and glmer to do it. Oh well.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
One more issue that puzzles me. For the lmer-format specification, I get:

system.time(communityPGLMM(count ~ habitat_type + elevation + wood_density + dbh + cd + bark_texture + (1|sp) + (1|site), family="binomial", sp = d$sp, site = d$site, data=d, cpp=F))
Error: Column `count` must be a 1d atomic vector or a list
Timing stopped at: 0.03 0.001 0.031

This doesn't happen for the long-form specification.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Can you send the data d to me?


On Oct 1, 2018, at 3:45 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

One more issue that puzzles me. For the lmer-format specification, I get:

system.time(communityPGLMM(count ~ habitat_type + elevation + wood_density + dbh + cd + bark_texture + (1|sp) + (1|site), family="binomial", sp = d$sp, site = d$site, data=d, cpp=F))
Error: Column `count` must be a 1d atomic vector or a list
Timing stopped at: 0.03 0.001 0.031

This doesn't happen for the long-form specification.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
I don't know if this has retained the format. "count" is of the form cbind(success, failure).

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Have you tried to replace count with  cbind(success, failure)?


On Oct 1, 2018, at 3:51 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't know if this has retained the format. "count" is of the form cbind(success, failure).

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
Same problem

communityPGLMM(cbind(success, failure) ~ 1 + (1|sp__) + (1|site), family="binomial", sp = d$sp, site = d$site, data=d, cpp=F)
Error: Column `count` must be a 1d atomic vector or a list

There seems to be some check on data=d.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Can you send the data d to me? I cannot debug without it. I have no problem here with my data.


On Oct 1, 2018, at 3:55 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

Same problem

communityPGLMM(cbind(success, failure) ~ 1 + (1|sp__) + (1|site), family="binomial", sp = d$sp, site = d$site, data=d, cpp=F)
Error: Column `count` must be a 1d atomic vector or a list

There seems to be some check on data=d.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Ok, internal cpp has LL exported.


On Oct 1, 2018, at 3:57 PM, Daijiang Li <dli1@ufl.edu<mailto:dli1@ufl.edu>> wrote:

Can you send the data d to me? I cannot debug without it. I have no problem here with my data.


On Oct 1, 2018, at 3:55 PM, Anthony R. Ives <notifications@github.com<mailto:notifications@github.com>> wrote:

Same problem

communityPGLMM(cbind(success, failure) ~ 1 + (1|sp__) + (1|site), family="binomial", sp = d$sp, site = d$site, data=d, cpp=F)
Error: Column `count` must be a 1d atomic vector or a list

There seems to be some check on data=d.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
I sent this before. Did you get it?


I don't know if this has retained the format. "count" is of the form cbind(success, failure).

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by arives** [comment]
Thanks!!

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Pull request merged**
